version: "3"
services:
  barber-spring:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=barber
    restart: unless-stopped